#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path=systemd --wait_until="Stopped"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_print_info "Modifying config file..."

config="$install_dir/.env"
ynh_backup_if_checksum_is_different "$config"

# Change the URL in the configuration file

if [ "$new_path" == "/" ]
then
	new_domain_uri="$new_domain"
else
	new_domain_uri="$new_domain$new_path"
fi

ynh_replace --match="EXTERNAL_URL=.*" --replace="EXTERNAL_URL=https://$new_domain_uri/" --file="$config"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================
ynh_print_info "Storing the config file checksum..."

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$config"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Started"

if ynh_in_ci_tests; then
	sleep 60
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
